name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown
          
      - name: Convert README to HTML
        run: |
          python -c "
          import markdown
          with open('README.md', 'r') as f:
              text = f.read()
          html = markdown.markdown(text, extensions=['fenced_code', 'tables'])
          with open('index_template.html', 'r') as f:
              template = f.read()
          final_html = template.replace('{{CONTENT}}', html)
          with open('index.html', 'w') as f:
              f.write(final_html)
          "
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
